Repository bellshade/SQL, pull requests merged in 2021-11, with the labels that each got.

#11 add:Lengkapi Penjelasan Introduction DB, DBMS DB relational
  SQL Intro/SQL_DB_Relational.md
  SQL Intro/SQL_Intro.md
Labels: markdown files, request docs team untuk review

#10 add:silabus atau roadmap bellshade sql
  Silabus.md
Labels: markdown files, request docs team untuk review

#15 add:insert into query
  Data Manipulation Language/INSERT.md
Labels: markdown files, request docs team untuk review

#19 fix:namefile md dan add ddl
  4-Data-Defintion-Language/1-CREATE.md
  4-Data-Defintion-Language/2-Show-Object.md
  4-Data-Defintion-Language/3-Alter-Object.md
  4-Data-Defintion-Language/4-Drop-Object.md
  4-Data-Defintion-Language/5-Truncate-Data.md
  SQL Intro/1_Intro_DB.md
  SQL Intro/2_DB_Relational.md
  SQL Intro/3_INTRO_SQL_QUERY.md
  SQL Intro/4_Data_Definitiom_Language.md
Labels: markdown files, request docs team untuk review

#39 add:sql comment
  01_Pengenalan/4-SQL Comment.md
Labels: markdown files, request docs team untuk review

#40 add: Menambahkan materi INNER JOIN
  10_Join_Table/1-Inner-Join.md
Labels: add, markdown files, request docs team untuk review

#22 Create sql table.md
  SQL TABLE/sql table.md
Labels: markdown files, request docs team untuk review

#42 fix: memperbaiki label docs-team menjadi sql-team
  .mergify.yml
Labels: bug, ready-to-merge, sudah direview !

#46 feat: menambahkan query update
  Basic/02_Data_Manipulation_Language/3_Mengupdate_Data/README.md
Labels: Ok to merge, ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review

#47 docs: menambahkan dokumentasi CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Ok to merge, ready-to-merge, documentation, markdown files, sudah direview !, request sql team untuk review

#48 fix: memperbaiki urutan folder
  Basic/09_Table/README.md
  Basic/11_GroupBy/README.md
  Basic/12_SQL_Schema/README.md
Labels: bug, ready-to-merge, markdown files, sudah direview !, request sql team untuk review
