Repository bellshade/SQL, pull requests merged in 2022-05, with the labels that each got.

#74 feat: menambah materi math round
  Basic/06_Numeric_Functions/6_Math_Round/README.md
Labels: ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review

#75 add: Menambah Materi UNION
  Basic/05_SQL_Operator/9_UNION/README.md
Labels: Ok to merge, ready-to-merge, documentation, add, markdown files, request docs team untuk review, sudah direview !, request sql team untuk review

#79 add: menambahkan materi math floor
  Basic/06_Numeric_Functions/8_Math_Floor/README.md
Labels: ready-to-merge, add, markdown files, sudah direview !, request sql team untuk review
