Repository bellshade/SQL, pull requests merged in 2022-02, with the labels that each got.

#59 feat: menambahkan meteri math count
  Basic/06_Numeric_Functions/1_Math_Count/README.md
Labels: Ok to merge, ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review

#57 feat: menambahkan materi OrderBy
  Basic/05_SQL_Operator/6_Limit/README.md
  Basic/05_SQL_Operator/7_OrderBy/README.md
  Basic/05_SQL_Operator/8_Distinct/README.md
Labels: ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review

#61 feat: menambah materi average
  Basic/06_Numeric_Functions/2_Math_Average/README.md
Labels: Ok to merge, ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review

#62 docs: memperbaiki dokumentasi sesuai EYD
  README.md
Labels: Ok to merge, ready-to-merge, documentation, markdown files, sudah direview !, request sql team untuk review

#64 feat: menambah materi math max min
  Basic/06_Numeric_Functions/3_Math_MinMax/README.md
Labels: Ok to merge, ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review

#66 feat: menambah materi math sum
  Basic/06_Numeric_Functions/4_Math_Sum/README.md
Labels: Ok to merge, ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review
