Repository bellshade/SQL, pull requests merged in 2022-10, with the labels that each got.

#82 feat: menambahkan materi SQL yaitu LEFT JOIN
  Basic/10_Join_Table/2_Left_Join/README.md
Labels: ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review, HACKTOBERFEST-ACCEPTED

#85 add: menambahkan dokumentasi Blob
  Basic/13_Blob/README.md
  README.md
Labels: Ok to merge, ready-to-merge, add, markdown files, sudah direview !, request sql team untuk review, HACKTOBERFEST-ACCEPTED

#90 add: menambahkan materi baru dan mengubah dokumen
  Basic/01_Pengenalan/5_Manipulasi_Database/README.md
  Basic/13_Blob/README.md
Labels: Ok to merge, ready-to-merge, add, markdown files, sudah direview !, request sql team untuk review

#91 add: penjelasan SQL SELECT DISTINCT
  Basic/02_Data_Manipulation_Language/1_Menampilkan_Data/README.md
Labels: Ok to merge, ready-to-merge, add, markdown files, sudah direview !, request sql team untuk review, HACKTOBERFEST-ACCEPTED

#92 docs: memperbaiki visitor badge
  README.md
Labels: documentation, markdown files, request sql team untuk review, HACKTOBERFEST-ACCEPTED

#94 feat: operator logika
  Basic/05_SQL_Operator/3_Operator_Logika/README.md
Labels: enhancement, markdown files, request sql team untuk review, HACKTOBERFEST-ACCEPTED

#95 feat: right join
  Basic/10_Join_Table/3_Right_Join/README.md
Labels: ready-to-merge, enhancement, markdown files, request sql team untuk review, HACKTOBERFEST-ACCEPTED
