Repository bellshade/SQL, pull requests merged in 2022-03, with the labels that each got.

#67 fix: memperbaiki typo
  Basic/06_Numeric_Functions/2_Math_Average/README.md
Labels: bug, ready-to-merge, markdown files, sudah direview !, request sql team untuk review

#69 feat: menambah materi SQRT
  Basic/06_Numeric_Functions/5_Math_SQRT/README.md
Labels: Ok to merge, ready-to-merge, enhancement, markdown files, sudah direview !, request sql team untuk review

#70 docs: menambahkan navigasi next dan back pada materi setiap repo
  Basic/01_Pengenalan/1_Pengenalan_Database/README.md
  Basic/01_Pengenalan/2_Pengenalan_Database_Relational/README.md
  Basic/01_Pengenalan/3_Pengenalan_Query_Database/README.md
  Basic/01_Pengenalan/4_SQL_Comment/README.md
  Basic/02_Data_Manipulation_Language/1_Menampilkan_Data/README.md
  Basic/02_Data_Manipulation_Language/2_Menginput_Data/README.md
  Basic/02_Data_Manipulation_Language/3_Mengupdate_Data/README.md
  Basic/02_Data_Manipulation_Language/4_Menghapus_Data/README.md
  Basic/03_Data_Defintion_Language/1_Membuat_Object/README.md
  Basic/03_Data_Defintion_Language/2_Menampilkan_Object/README.md
  Basic/03_Data_Defintion_Language/3_Modifikasi_Object/README.md
  Basic/03_Data_Defintion_Language/4_Menghapus_Object/README.md
  Basic/03_Data_Defintion_Language/5_Menghilangkan_Data_Dalam_Object/README.md
  Basic/04_Data_Control_Language/1_Menerima_Akses/README.md
  Basic/04_Data_Control_Language/2_Menolak_Akses/README.md
  Basic/05_SQL_Operator/1_Operator_Aritmatika/README.md
  Basic/05_SQL_Operator/2_Operator_Perbandingan/README.md
  Basic/05_SQL_Operator/5_Aliasing/README.md
  Basic/05_SQL_Operator/6_Limit/README.md
  Basic/05_SQL_Operator/7_OrderBy/README.md
  Basic/05_SQL_Operator/8_Distinct/README.md
Labels: documentation, markdown files, request sql team untuk review
